package lanectl

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	sshMarker  = "# pathfinder-lane"
	sshInclude = "Include"
)

// SSHConfigPath is ~/.pathfinder-crt/ssh_config
func SSHConfigPath(appHome string) string {
	return filepath.Join(appHome, "ssh_config")
}

type SSHHost struct {
	Alias     string
	Folder    string
	Host      string
	Port      int
	User      string
	FrontPort int
	Via       string // "proxy" or "agent"
	JumpHost  string
	JumpPort  int
	JumpUser  string
}

func RenderSSHConfig(laneBin string, hosts []SSHHost) string {
	var b strings.Builder
	b.WriteString(sshMarker + " — generated by pflane create. Do not edit; re-run create-all.\n")
	b.WriteString("# OpenSSH: ssh <alias>  (ProxyCommand ensures VPN — no daemon)\n")
	b.WriteString("# SecureCRT still needs: pflane serve\n\n")

	type jumpKey struct {
		folder, host string
		port         int
	}
	jumpAlias := map[jumpKey]string{}
	seenJump := map[string]bool{}
	for _, h := range hosts {
		jh := strings.TrimSpace(h.JumpHost)
		if jh == "" || h.Via == "agent" {
			continue
		}
		jp := h.JumpPort
		if jp <= 0 {
			jp = 22
		}
		k := jumpKey{folder: h.Folder, host: jh, port: jp}
		if _, ok := jumpAlias[k]; ok {
			continue
		}
		alias := SSHAlias(h.Folder, "jump-"+jh)
		if seenJump[alias] {
			alias = fmt.Sprintf("%s-%d", alias, jp)
		}
		seenJump[alias] = true
		jumpAlias[k] = alias
		b.WriteString("Host " + alias + "\n")
		if h.JumpUser != "" {
			b.WriteString("  User " + h.JumpUser + "\n")
		}
		b.WriteString("  HostName " + jh + "\n")
		b.WriteString("  Port " + strconv.Itoa(jp) + "\n")
		b.WriteString("  ProxyCommand " + LaneProxyCommand(laneBin, h.Folder, "%h", "%p") + "\n")
		b.WriteString("  HostKeyAlias " + jh + "\n\n")
	}

	seen := map[string]int{}
	for _, h := range hosts {
		alias := h.Alias
		if n := seen[alias]; n > 0 {
			alias = fmt.Sprintf("%s-%d", alias, n+1)
		}
		seen[h.Alias]++
		port := h.Port
		if port <= 0 {
			port = 22
		}
		b.WriteString("Host " + alias + "\n")
		if h.User != "" {
			b.WriteString("  User " + h.User + "\n")
		}
		if h.Via == "agent" && h.FrontPort > 0 {
			b.WriteString("  HostName 127.0.0.1\n")
			b.WriteString("  Port " + strconv.Itoa(h.FrontPort) + "\n")
		} else if ja := jumpAlias[jumpKey{folder: h.Folder, host: strings.TrimSpace(h.JumpHost), port: jumpPort(h)}]; ja != "" && h.Via != "agent" {
			b.WriteString("  HostName " + h.Host + "\n")
			b.WriteString("  Port " + strconv.Itoa(port) + "\n")
			b.WriteString("  ProxyJump " + ja + "\n")
		} else {
			b.WriteString("  HostName " + h.Host + "\n")
			b.WriteString("  Port " + strconv.Itoa(port) + "\n")
			b.WriteString("  ProxyCommand " + LaneProxyCommand(laneBin, h.Folder, "%h", "%p") + "\n")
		}
		if h.Host != "" && h.Host != "127.0.0.1" {
			b.WriteString("  HostKeyAlias " + h.Host + "\n")
		}
		b.WriteByte('\n')
	}
	return b.String()
}

func jumpPort(h SSHHost) int {
	if h.JumpPort > 0 {
		return h.JumpPort
	}
	if strings.TrimSpace(h.JumpHost) != "" {
		return 22
	}
	return 0
}

func LaneProxyCommand(bin, folder, hostTok, portTok string) string {
	if strings.TrimSpace(bin) == "" {
		bin = "pflane"
	}
	bin = strings.ReplaceAll(bin, `\`, `/`)
	quoted := bin
	if strings.ContainsAny(bin, " ") {
		quoted = `"` + bin + `"`
	}
	if hostTok == "" {
		hostTok = "%h"
	}
	if portTok == "" {
		portTok = "%p"
	}
	return fmt.Sprintf("%s proxy -folder %s -host %s -port %s", quoted, shellWord(strings.TrimSpace(folder)), hostTok, portTok)
}

func shellWord(s string) string {
	if s == "" {
		return `""`
	}
	if !strings.ContainsAny(s, " \t\"'") {
		return s
	}
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}

func WriteSSHConfig(appHome, laneBin string, hosts []SSHHost) (string, error) {
	path := SSHConfigPath(appHome)
	if err := os.MkdirAll(appHome, 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(RenderSSHConfig(laneBin, hosts)), 0o644); err != nil {
		return "", err
	}
	return path, EnsureSSHInclude(path)
}

func userSSHConfig() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	return filepath.Join(dir, "config"), nil
}

// EnsureSSHInclude appends one Include of the generated file to ~/.ssh/config.
func EnsureSSHInclude(laneFile string) error {
	cfg, err := userSSHConfig()
	if err != nil {
		return err
	}
	raw, _ := os.ReadFile(cfg)
	text := string(raw)
	want := filepath.ToSlash(laneFile)
	if strings.Contains(text, want) || strings.Contains(text, sshMarker) {
		return nil
	}
	line := "\n" + sshMarker + "\nInclude " + want + "\n"
	if !strings.HasSuffix(text, "\n") && text != "" {
		line = "\n" + strings.TrimPrefix(line, "\n")
	}
	f, err := os.OpenFile(cfg, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(line)
	return err
}
